title: Priya Kumari # your name (or website title) here
logo: "Priyakr14.github.io/images/pp.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  University of Cincinnati - MS Business Analytics 
  <br><br>
  3 years of experience in Analytics Field 
  <br><br>
  <a href="https://www.linkedin.com/in/priyakumaripk/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
