title: Priya Kumari # your name (or website title) here
logo: "Priyakr14.github.io/images/pp.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduated from the University of Cincinnati with MS in Business Analytics 
  <br><br>
  3+ years of experience in Analytics Field. Specialized in building analytical solutions for Product Development Projects. 
  <br><br>
  <a href="https://www.linkedin.com/in/priyakumaripk/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-architect
